name: "Jenkins-Action"
description: "Start Jenkins jobs and report back URL and status of build"
author: "Josh Levy-Kramer"
inputs:
  url:
    description: "Jenkins URL including http/https protocol"
    required: true
  job_name:
    description: "Jenkins job name to build"
    required: true
  username:
    description: "Jenkins username"
    required: false
  api_token:
    description: "Jenkins API token"
    required: false
  parameters:
    description: 'Build parameters in JSON format e.g. `{"field1":"value1"}`'
    required: false
  cookies:
    description: 'Cookies to include in HTTP requests in JSON format e.g. `{"field1":"value1"}`'
    required: false
  wait:
    description: "Should the runner wait for the build to finish and provide ok status"
    required: false
    default: "True"
  timeout:
    description: "Timeout in seconds for build to complete"
    required: false
    default: "600"
  start_timeout:
    description: "Timeout in seconds for build to start"
    required: false
    default: "600"
  interval:
    description: "How frequently in seconds to query Jenkins for build status"
    required: false
    default: "5"
  image_address:
    description: "Docker image address including ECR part"
    required: true
outputs:
  build_url:
    description: "Jenkins build URL"


runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Pull Docker image
      run: docker pull ${{ inputs.image_address }}
      shell: bash

    - name: Run Docker container
      shell: bash
      run: |
        docker run -e URL=${{ inputs.url }} \
                   -e JOB_NAME=${{ inputs.job_name }} \
                   -e USERNAME=${{ inputs.username }} \
                   -e API_TOKEN=${{ inputs.api_token }} \
                   -e PARAMETERS=${{ inputs.parameters }} \
                   -e COOKIES=${{ inputs.cookies }} \
                   -e WAIT=${{ inputs.wait }} \
                   -e TIMEOUT=${{ inputs.timeout }} \
                   -e START_TIMEOUT=${{ inputs.start_timeout }} \
                   -e INTERVAL=${{ inputs.interval }} \
                   ${{ inputs.image_address }}